### PR TITLE
Add offsetted columns

### PR DESCRIPTION
**Pull request by aluuu**
Hello,

It will be great if you review my changes. I'm not quite satisfied with these monstrous function type signatures.

### CODE REVIEW

**Comment by rehno-lindeque** [comment]
Hi @aluuu, I think it's alright - thank you for the PR!

Using the functions seem relatively concise

``` elm
colMdOffset_ 3 2 2 1 1 1
  [ div_ {- ... -}
  ]
colMdOffset_ xs xs_offset sm sm_offset md md_offset 
```

versus the html

``` html
<div class="col-xs-3 col-xs-offset-2 col-sm-2 col-sm-offset-1 col-md-1 col-md-offset-1"> 
  <div> ... </div>
</div>
```

...as long as you understand the convention that numbers always go from `xs` up to (in this case) `md`.

I had a similar concern in `elm-html-shorthand` that things were getting too difficult to understand and made many elements accept records instead, however I don't think it's necessary in this case - I might try and document the convention at some point though.

**Comment by rehno-lindeque** [comment]
I published to [6.1.0](http://package.elm-lang.org/packages/circuithub/elm-bootstrap-html/6.1.0/Bootstrap-Html#colXsOffset_) because I think this is immediately useful.

However, something that is missing is `0` offsets since bootstrap naturally doesn't have `col-..-offset-0` classes. This will make it a little bit difficult to use in this interleaved fashion since there is no way to write this at the moment:

``` elm
colMdOffset_ 3 0 2 0 1 1
```

to generate

``` html
<div class="col-xs-3 col-sm-2 col-md-1 col-md-offset-1"> 
```

If you have some extra time, would you mind submitting another PR for that?

**Comment by aluuu** [comment]
Sure. I'll try to do it tomorrow.

**Comment by rehno-lindeque** [comment]
PS another api that might be worth considering is:

``` elm
colMdOffset_ (3,0) (2,0) (1,1)
```

I can't tell whether the extra reading comprehension is worth it though, I generally prefer less noise to avoid stress on my hands.

**Pull request merged**
