### PR TITLE
Remove mention of skipNavigation' which did not exist I think

### PR DESCRIPTION
**Pull request by meclav**
and bump the package. The library looks really useful to me and I wanted to bring the newest version to the package repository. There's a conflict on one function not being published, which did not show up when I did elm package diff, so I think it didn't exist. before.

### CODE REVIEW

**Comment by rehno-lindeque** [comment]
Thank you! Do you mean that you'd like to bring it up to date with Elm `0.15.1`? It might be worth having a look at what @codedmart did for https://github.com/circuithub/elm-html-shorthand/pull/5.

> The library looks really useful to me

Honestly, it still needs quite a bit of work to approach full out bootstrap (and bootstrap has already released a new major version in the mean time), I actually think it might be worth trying to auto-generate some parts of it... I initially tried to cover bootstrap because I thought I might be able to do it quickly with some vim/sublime hacking, but in retrospect it doesn't look like it's all that easy.

To be honest I'm not even sure if CircuitHub will stick with bootstrap in our next major iteration - we will have to see. There are so many great options out there now...

**Comment by rehno-lindeque** [comment]
Published [6.3.2](http://package.elm-lang.org/packages/circuithub/elm-bootstrap-html/6.3.2/Bootstrap-Html)

**Comment by meclav** [comment]
I was far less ambitious than that, I use evancz/elm-html and picked up the new version when I was starting and this has a dependency.

Putting bootstrap's classes in did look like an easy win especially because what I need is quite limited - out of the box css, the containers / grid system. This package seems to have it. If I find something I need that isn't there, I'll try and add it!

Thanks for the merge and making this package in the first place.

**Comment by rehno-lindeque** [comment]
> If I find something I need that isn't there, I'll try and add it!

That would be great! I also add stuff as I find I need it at the moment. My initial idea was to quickly do all/as much of the css as I can handle and then let the community port the javascript widgets (publicly crediting each person for their particular component). Looking at things like polymer etc I think we can do better than bootstrap though. (I haven't had time to experiment though, who knows bootstrap v4 might be awesome)

**Pull request merged**
